SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT deptname FROM department WHERE deptno='?';

SELECT LOCATION FROM department WHERE deptno='?';

SELECT MGRNO FROM department WHERE deptno='?';

SELECT E.EMPNO, E.FIRSTNME, E.LASTNAME FROM EMPLOYEE E, DEPARTMENT D WHERE E.WORKDEPT=D.DEPTNO AND E.EMPNO='000050';


