SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT deptname INTO v_deptname FROM department WHERE deptno=v_deptno;
SELECT LOCATION INTO v_location FROM department WHERE deptno=v_deptno;
SELECT MGRNO INTO v_mgrno FROM department WHERE deptno=v_deptno;
SELECT E.EMPNO, E.FIRSTNME, E.LASTNAME INTO V_EMPNO, V_FIRSTNME, V_LASTNAME FROM EMPLOYEE E, DEPARTMENT D WHERE E.WORKDEPT=D.DEPTNO AND E.EMPNO='000050';
