INSERT INTO DB2ADMIN.DEPARTMENT (DEPTNO, DEPTNAME, MGRNO, ADMRDEPT, LOCATION) VALUES ('X00', 'SPIFFY COMPUTER SERVICE DIV.', '000010', 'A00', NULL);
INSERT INTO DB2ADMIN.DEPARTMENT (DEPTNO, DEPTNAME, MGRNO, ADMRDEPT, LOCATION) VALUES ('z00', 'SPIFFY COMPUTER SERVICE DIV.', '000010', 'A00', NULL);
